### ISSUE TITLE
i get error: undefined reference to '__gnu_mcount_nc' please

### ISSUE THREAD

**Issue by qiutaoleo** [richq/android-ndk-profiler#2]
i used cocos2dx with ndk r10 (64-bit) get this error

[armeabi] StaticLibrary  : libextension.a
[armeabi] StaticLibrary  : libcocos2dxinternal.a
[armeabi] StaticLibrary  : libbox2d.a
[armeabi] StaticLibrary  : libluacocos2dandroid.a
[armeabi] StaticLibrary  : libcpufeatures.a
[armeabi] StaticLibrary  : libcocos2dandroid.a
[armeabi] SharedLibrary  : libcocos2dlua.so
jni/../../Classes/protobuf-lite/google/protobuf/generated_message_util.cc:43: error: undefined reference to '__gnu_mcount_nc'
jni/../../Classes/protobuf-lite/google/protobuf/generated_message_util.cc:46: error: undefined reference to '__gnu_mcount_nc'
jni/../../Classes/protobuf-lite/google/protobuf/generated_message_util.cc:54: error: undefined reference to '__gnu_mcount_nc'
jni/../../Classes/protobuf-lite/google/protobuf/stubs/once.cc:65: error: undefined reference to '__gnu_mcount_nc'
jni/hellolua/main.cpp:16: error: undefined reference to 'monstartup'
jni/hellolua/main.cpp:18: error: undefined reference to 'moncleanup'
collect2.exe: error: ld returned 1 exit status
make.exe: *** [obj/local/armeabi/libcocos2dlua.so] Error 1

I'm not familiar with android ndk

**Comment by richq** [comment]
Sadly, only 32-bit is supported.
