### ISSUE TITLE
conflict definition of ucontext with ndk-r10d

### ISSUE THREAD

**Issue by Flamaros** [richq/android-ndk-profiler#34]
Switching from ndk-r9d to ndk-r10d give me some conflicts with ucontext struct definition.

**Comment by richq** [comment]
Thanks for nudging me on this. I've updated to the latest NDK and fixed the problem. Release 3.3.1 (or current master) should work OK.

**Comment by Flamaros** [comment]
It's fine for me. Thanks a lot.
